### ISSUE TITLE
[CLDR v38+] Don't fail when parsing `c`/`e` plural rule operands

### ISSUE THREAD

**Issue by movermeyer** [ruby-i18n/ruby-cldr#63]
ruby-cldr fails to export CLDR v38:

```bash
ruby-cldr (master)$ thor cldr:download --source=http://unicode.org/Public/cldr/38/core.zip
ruby-cldr (master)$ thor cldr:export
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Traceback (most recent call last):
	41: from /Users/username/.gem/ruby/2.7.1/bin/thor:23:in `<main>'
	40: from /Users/username/.gem/ruby/2.7.1/bin/thor:23:in `load'
	39: from /Users/username/.gem/ruby/2.7.1/gems/thor-1.0.1/bin/thor:6:in `<top (required)>'
	38: from /Users/username/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	37: from /Users/username/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	36: from /Users/username/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	35: from /Users/username/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor/command.rb:135:in `run'
	34: from /Users/username/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor/command.rb:29:in `run'
	33: from /Users/username/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor/runner.rb:43:in `method_missing'
	32: from /Users/username/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	31: from /Users/username/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	30: from /Users/username/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	29: from /Users/username/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	28: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/thor.rb:27:in `export'
	27: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export.rb:70:in `export'
	26: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export.rb:70:in `each'
	25: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export.rb:71:in `block in export'
	24: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export.rb:71:in `each'
	23: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export.rb:72:in `block (2 levels) in export'
	22: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/ruby.rb:5:in `export'
	21: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export.rb:85:in `data'
	20: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export.rb:110:in `plural_data'
	19: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export.rb:96:in `locale_based_data'
	18: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export.rb:96:in `inject'
	17: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export.rb:96:in `each'
	16: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export.rb:97:in `block in locale_based_data'
	15: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export.rb:97:in `new'
	14: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals.rb:28:in `initialize'
	13: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals.rb:32:in `to_hash'
	12: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals/rules.rb:105:in `to_ruby'
	11: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals/rules.rb:105:in `inject'
	10: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals/rules.rb:105:in `each'
	 9: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals/rules.rb:106:in `block in to_ruby'
	 8: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals/rules.rb:69:in `parse'
	 7: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals/rules.rb:69:in `inject'
	 6: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals/rules.rb:69:in `each'
	 5: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals/rules.rb:69:in `block in parse'
	 4: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals/rules.rb:71:in `parse'
	 3: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals/rules.rb:71:in `inject'
	 2: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals/rules.rb:71:in `each'
	 1: from /Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals/rules.rb:71:in `block in parse'
/Users/username/src/ruby-i18n/ruby-cldr/lib/cldr/export/data/plurals/rules.rb:80:in `parse': can not parse 'e = 0 ' (RuntimeError)
```

It seems that CLDR v38 may have changed the syntax of plural rules, and it affects the `fr` locale:

* In [v38](https://github.com/unicode-org/cldr/blob/22abbd935b7e5f02d8a3604f69dc0d0ffe7b3863/common/supplemental/plurals.xml#L118):

```xml
        <!-- 3: one,many,other -->

        <pluralRules locales="fr">
            <pluralRule count="one">i = 0,1 @integer 0, 1 @decimal 0.0~1.5</pluralRule>
            <pluralRule count="many">e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5 @integer 1000000, 1e6, 2e6, 3e6, 4e6, 5e6, 6e6, … @decimal 1.0000001e6, 1.1e6, 2.0000001e6, 2.1e6, 3.0000001e6, 3.1e6, …</pluralRule>
            <pluralRule count="other"> @integer 2~17, 100, 1000, 10000, 100000, 1e3, 2e3, 3e3, 4e3, 5e3, 6e3, … @decimal 2.0~3.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, 1.0001e3, 1.1e3, 2.0001e3, 2.1e3, 3.0001e3, 3.1e3, …</pluralRule>
        </pluralRules>
```

* In v37: 

```xml
        <pluralRules locales="ff fr hy kab">
            <pluralRule count="one">i = 0,1 @integer 0, 1 @decimal 0.0~1.5</pluralRule>
            <pluralRule count="other"> @integer 2~17, 100, 1000, 10000, 100000, 1000000, … @decimal 2.0~3.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …</pluralRule>
        </pluralRules>
```

Note the addition of the `e = 0` syntax. (I haven't yet looked into the details of what it means).

**Comment by cejaekl** [comment]
The new operand `e` is defined [here](http://unicode.org/reports/tr35/tr35-numbers.html#Operands) as follows:

Symbol | Value
-- | --
n | absolute value of the source number.
i | integer digits of n.
v | number of visible fraction digits in n, with trailing zeros.*
w | number of visible fraction digits in n, without trailing zeros.*
f | visible fraction digits in n, with trailing zeros.*
t | visible fraction digits in n, without trailing zeros.*
c | compact decimal exponent value: exponent of the power of 10 used in compact decimal formatting.
e | currently, synonym for ‘c’. however, may be redefined in the future.

Changing [this](https://github.com/ruby-i18n/ruby-cldr/blob/f7a5045b3e6ff557cd0021ac19ae7ff4525db3d0/lib/cldr/export/data/plurals/rules.rb#L63) line from
```ruby
operand = /(n|i|f|t|v|w)/i
```
to
```ruby
operand = /(e|n|i|f|t|v|w)/i
```
(in other words, adding `e` to the list of known operands) enables ruby-cldr to successfully export CLDR v39.

Adding `c` as well probably wouldn't hurt, but doesn't seem to be necessary for v39.

**Comment by movermeyer** [comment]
Fixed by https://github.com/ruby-i18n/ruby-cldr/pull/130
